version: "3"

services:
  next-app:
    container_name: geminipro-next-web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    environment:
      - GOOGLE_API_KEY=$GOOGLE_API_KEY
      - GOOGLE_URL=$GOOGLE_URL
      - NODE_ENV=production
    restart: always
    ports:
      - 3000
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.my-nextjs-app-http.rule=Host(`chatgg.co`)"
      - "traefik.http.routers.my-nextjs-app-http.entrypoints=web"
      - "traefik.http.routers.my-nextjs-app-http.middlewares=https-redirect"
      - "traefik.http.routers.my-nextjs-app.rule=Host(`chatgg.co`)"
      - "traefik.http.routers.my-nextjs-app.entrypoints=websecure"
      - "traefik.http.routers.my-nextjs-app.tls.certResolver=letsencrypt"
      - "traefik.http.services.my-nextjs-app.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"
    deploy:
      resources:
        limits:
          memory: 256M
networks:
  dokploy-network:
    external: true